swagger: '2.0'
info:
  title: Arbiter - Legacy REST and gRPC Gateway docs
  description: A REST interface for state queries, legacy transactions
  version: 1.0.0
paths:
  /errata/audit/v1beta1/protocol:
    get:
      operationId: Protocol
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              source_code:
                type: string
              project_home:
                type: string
              category:
                type: string
              attack_pool:
                type: string
              defense_pool:
                type: string
        default:
          description: An unexpected error response
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: id
          in: query
          required: false
          type: string
          format: uint64
      tags:
        - Query
definitions:
  errata.audit.v1beta1.QueryProtocolResponse:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      source_code:
        type: string
      project_home:
        type: string
      category:
        type: string
      attack_pool:
        type: string
      defense_pool:
        type: string
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
